name: AutoDocAI Upload

on:
  push:
    branches:
      - main

jobs:
  autodoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip the repo
        run: zip -r project.zip . -x "*.git*" "*.venv*" "__pycache__/*"

      - name: Debug zip output
        run: |
          ls -lh
          file project.zip
      - name: Send to AutoDocAI 
        run: |
          echo "Current directory: $(pwd)"
          ls -lh
          curl -f -i -X POST https://autodocai.net/generate-docs/secure/ \
            -H "X-API-Key: ${{ secrets.AUTODOC_API_KEY }}" \
            -F file=@project.zip